/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as WidgetsTypeAddressRouteImport } from './routes/widgets/$type.$address'
import { Route as ApiDonationTestRouteImport } from './routes/api/donation/test'
import { Route as ApiDonationRecordRouteImport } from './routes/api/donation/record'
import { Route as ApiAuthVerifyRouteImport } from './routes/api/auth/verify'
import { Route as ApiAuthNonceRouteImport } from './routes/api/auth/nonce'
import { Route as ApiAuthMeRouteImport } from './routes/api/auth/me'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthClaimUsernameRouteImport } from './routes/api/auth/claim-username'
import { Route as ApiAuthCheckUsernameRouteImport } from './routes/api/auth/check-username'
import { Route as ApiAuthAblyTokenRouteImport } from './routes/api/auth/ably-token'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetsTypeAddressRoute = WidgetsTypeAddressRouteImport.update({
  id: '/widgets/$type/$address',
  path: '/widgets/$type/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationTestRoute = ApiDonationTestRouteImport.update({
  id: '/api/donation/test',
  path: '/api/donation/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDonationRecordRoute = ApiDonationRecordRouteImport.update({
  id: '/api/donation/record',
  path: '/api/donation/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthVerifyRoute = ApiAuthVerifyRouteImport.update({
  id: '/api/auth/verify',
  path: '/api/auth/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthNonceRoute = ApiAuthNonceRouteImport.update({
  id: '/api/auth/nonce',
  path: '/api/auth/nonce',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMeRoute = ApiAuthMeRouteImport.update({
  id: '/api/auth/me',
  path: '/api/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthClaimUsernameRoute = ApiAuthClaimUsernameRouteImport.update({
  id: '/api/auth/claim-username',
  path: '/api/auth/claim-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthCheckUsernameRoute = ApiAuthCheckUsernameRouteImport.update({
  id: '/api/auth/check-username',
  path: '/api/auth/check-username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthAblyTokenRoute = ApiAuthAblyTokenRouteImport.update({
  id: '/api/auth/ably-token',
  path: '/api/auth/ably-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/ably-token': typeof ApiAuthAblyTokenRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/claim-username': typeof ApiAuthClaimUsernameRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donation/record': typeof ApiDonationRecordRoute
  '/api/donation/test': typeof ApiDonationTestRoute
  '/widgets/$type/$address': typeof WidgetsTypeAddressRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/ably-token': typeof ApiAuthAblyTokenRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/claim-username': typeof ApiAuthClaimUsernameRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donation/record': typeof ApiDonationRecordRoute
  '/api/donation/test': typeof ApiDonationTestRoute
  '/widgets/$type/$address': typeof WidgetsTypeAddressRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/setup': typeof SetupRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/u/$username': typeof UUsernameRoute
  '/api/auth/ably-token': typeof ApiAuthAblyTokenRoute
  '/api/auth/check-username': typeof ApiAuthCheckUsernameRoute
  '/api/auth/claim-username': typeof ApiAuthClaimUsernameRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/me': typeof ApiAuthMeRoute
  '/api/auth/nonce': typeof ApiAuthNonceRoute
  '/api/auth/verify': typeof ApiAuthVerifyRoute
  '/api/donation/record': typeof ApiDonationRecordRoute
  '/api/donation/test': typeof ApiDonationTestRoute
  '/widgets/$type/$address': typeof WidgetsTypeAddressRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/setup'
    | '/api/uploadthing'
    | '/u/$username'
    | '/api/auth/ably-token'
    | '/api/auth/check-username'
    | '/api/auth/claim-username'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
    | '/api/donation/record'
    | '/api/donation/test'
    | '/widgets/$type/$address'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/setup'
    | '/api/uploadthing'
    | '/u/$username'
    | '/api/auth/ably-token'
    | '/api/auth/check-username'
    | '/api/auth/claim-username'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
    | '/api/donation/record'
    | '/api/donation/test'
    | '/widgets/$type/$address'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/setup'
    | '/api/uploadthing'
    | '/u/$username'
    | '/api/auth/ably-token'
    | '/api/auth/check-username'
    | '/api/auth/claim-username'
    | '/api/auth/logout'
    | '/api/auth/me'
    | '/api/auth/nonce'
    | '/api/auth/verify'
    | '/api/donation/record'
    | '/api/donation/test'
    | '/widgets/$type/$address'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  SetupRoute: typeof SetupRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiAuthAblyTokenRoute: typeof ApiAuthAblyTokenRoute
  ApiAuthCheckUsernameRoute: typeof ApiAuthCheckUsernameRoute
  ApiAuthClaimUsernameRoute: typeof ApiAuthClaimUsernameRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthMeRoute: typeof ApiAuthMeRoute
  ApiAuthNonceRoute: typeof ApiAuthNonceRoute
  ApiAuthVerifyRoute: typeof ApiAuthVerifyRoute
  ApiDonationRecordRoute: typeof ApiDonationRecordRoute
  ApiDonationTestRoute: typeof ApiDonationTestRoute
  WidgetsTypeAddressRoute: typeof WidgetsTypeAddressRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widgets/$type/$address': {
      id: '/widgets/$type/$address'
      path: '/widgets/$type/$address'
      fullPath: '/widgets/$type/$address'
      preLoaderRoute: typeof WidgetsTypeAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donation/test': {
      id: '/api/donation/test'
      path: '/api/donation/test'
      fullPath: '/api/donation/test'
      preLoaderRoute: typeof ApiDonationTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/donation/record': {
      id: '/api/donation/record'
      path: '/api/donation/record'
      fullPath: '/api/donation/record'
      preLoaderRoute: typeof ApiDonationRecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/verify': {
      id: '/api/auth/verify'
      path: '/api/auth/verify'
      fullPath: '/api/auth/verify'
      preLoaderRoute: typeof ApiAuthVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/nonce': {
      id: '/api/auth/nonce'
      path: '/api/auth/nonce'
      fullPath: '/api/auth/nonce'
      preLoaderRoute: typeof ApiAuthNonceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/me': {
      id: '/api/auth/me'
      path: '/api/auth/me'
      fullPath: '/api/auth/me'
      preLoaderRoute: typeof ApiAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/claim-username': {
      id: '/api/auth/claim-username'
      path: '/api/auth/claim-username'
      fullPath: '/api/auth/claim-username'
      preLoaderRoute: typeof ApiAuthClaimUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/check-username': {
      id: '/api/auth/check-username'
      path: '/api/auth/check-username'
      fullPath: '/api/auth/check-username'
      preLoaderRoute: typeof ApiAuthCheckUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/ably-token': {
      id: '/api/auth/ably-token'
      path: '/api/auth/ably-token'
      fullPath: '/api/auth/ably-token'
      preLoaderRoute: typeof ApiAuthAblyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  SetupRoute: SetupRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  UUsernameRoute: UUsernameRoute,
  ApiAuthAblyTokenRoute: ApiAuthAblyTokenRoute,
  ApiAuthCheckUsernameRoute: ApiAuthCheckUsernameRoute,
  ApiAuthClaimUsernameRoute: ApiAuthClaimUsernameRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthMeRoute: ApiAuthMeRoute,
  ApiAuthNonceRoute: ApiAuthNonceRoute,
  ApiAuthVerifyRoute: ApiAuthVerifyRoute,
  ApiDonationRecordRoute: ApiDonationRecordRoute,
  ApiDonationTestRoute: ApiDonationTestRoute,
  WidgetsTypeAddressRoute: WidgetsTypeAddressRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
